server:
  port: 8229

spring:
  application:
    name: oops-tabuyos-user

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@oops-eureka:8761/eureka/
    enabled: true
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}