server:
  port: 8231

spring:
  application:
    name: oops-oauth2-resource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      port: 35738
  security:
    user:
      name: root
      password: root

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:8230/oauth2/keys

