server:
  port: 7979

spring:
  application:
    name: oops-gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: lb://oops-tabuyos-order
          predicates:
            - Path=/tabuyos/order/**
          filters:
            - StripPrefix=1
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      port: 35736
  security:
    user:
      name: root
      password: root

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@oops-eureka:8761/eureka/
    enabled: true
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
